public class Class01 {

    public static void main(String[] args) {

        // V1 Çalışmalarım...
        // V2 Kodları...
        // V3 Çalışmalar..
        // V4
        // GitHub değişiklikleri...
        // Local'den Sevgilerle...
        // V5...
        // V6...
        // V7 remote...
    }
}
